### ISSUE TITLE
about pretrain models details

### ISSUE THREAD

**Issue by BrownSweater** [rwightman/pytorch-pretrained-gluonresnet#1]
Thanks providing pretrain models of pytorch.
but you report the result is different from gluoncv.
I want to understand the reasons for these differences.
can you open more details for convert gluoncv weights to pytorch.

**Comment by rwightman** [comment]
The weights are pretty much directly copied, very little difference between layouts and layers btw PyTorch and Gluon. That being said, at the low levels, small differences in order of operations and float rounding differences can accumulate. Also, gluoncv uses OpenCV image preprocessing and PyTorch uses PIL. Switching between those or changing the interpolation within those can change results +-0.5% or more in some cases.
